CRAN Resubmission
MD-Anderson-Bioinformatics/tsvio pull request #3
Opened 2023-09-25 16:27 UTC by marohrdanz

These changes were made in response to CRAN's reviewers and to pass automated build checks on CRAN's servers.

A few notable changes:

- Change `strcpy()` to `strncpy()` (75b6f3c)
  - This is to prevent buffer overflow errors on CRAN's Debian builds
- List Paul Hsieh as contributor because of `SuperFastHash()` (bb26367)
  - Also made minor changes to satisfy [GNU LGPL](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt)
- Add `\value` entry for tsvGenIndex. (74e9510)
- Improve Description (21638fa)

Items for us to discuss before resubmission:

- Further improvements to Description
- Licensing

2023-09-25 17:13 UTC, jmelott requested changes
Maybe add something to the description about how it creates an index file to the rows of the matrix which allows C code to read individual rows from the matrix file in non-sequential order without having to load all of the matrix into memory.  Maybe also some comments on the format of the data that is returned might be useful as well.

2023-09-26 21:55 UTC, marohrdanz commented
@jmelott I updated the Description.

2023-09-27 14:28 UTC, jmelott approved these changes

2023-09-28 03:44 UTC, ChrisWakefield approved these changes
This looks good.
Note this WIN32 implementation of mkstemp has this limitation:
"_mktemp_s can create a maximum of 26 unique file names for any given combination of base and nameTemplate values."  This should be ok for our use.

2023-09-29 13:27 UTC, merged